### PR TITLE
Various test fixes

### PR DESCRIPTION
**Pull request by sdanailo-42**
There are some tests which make no sense and also some tests which are important, but are missing.

### CODE REVIEW

**Review by zstenger93 — CHANGES_REQUESTED** [review]
Replacing
`cd /Users/"$USER"/Desktop/`
to
`cd /home/"$USER"/Desktop/`
is not really a solution.
I haven't thought about this before, but for example we are using MAC atm on the campus.
Could you rather add a check to them for the system and use the correct one based on that?

**Comment by sdanailo-42** [comment]
> I haven't thought about this before, but for example we are using MAC atm on the campus.

Ah, I forgot about that as well.

> Could you rather add a check to them for the system and use the correct one based on that?

Sure, I'll try something in a minute.

**Comment by sdanailo-42** [comment]
> Sure, I'll try something in a minute.

Maybe we can try doing this instead?

`cd "$HOME"/Desktop/`
`cd "$H"O"ME"/Desktop/`

**Comment by zstenger93** [comment]
> > Sure, I'll try something in a minute.
> 
> Maybe we can try doing this instead?
> 
> `cd "$HOME"/` `cd "$H"O"ME"/`
> 
> What does HOME on a MAC point to?

it's `/Users/user` so for example `echo $HOME` in my case is `/Users/zstenger`. It should work I guess.

**Comment by sdanailo-42** [comment]
> It should work I guess.

Done, for now I can't think of anything else.

**Review by zstenger93 — APPROVED** [review]

**Pull request merged**
